# Python Numpy Tutorial （来自cs231n）

reference: http://cs231n.github.io/python-numpy-tutorial/ 

We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

# Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode(伪代码), since it allows you to express very powerful ideas in very few lines of code while being very readable. 

## Basic data types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

**Numbers**:integers and floats work as you would expect from other languages:

In [7]:
x = 3
print(type(x))
print(x, x+1, x-1, x * 2, x ** 2)
x += 1
print(x)
x *= 2
print(x)
y = 2.5
print(type(y))
print(y, y+1, y*2, y**2)

<class 'int'>
3 4 2 6 9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment `(x++)` or decrement `(x--)` operators.(自增自减)

**Booleans**: Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):(Python实现了所有的布尔逻辑，但用的是英语(and, or, not)，而不是我们习惯的操作符)

In [8]:
t = True
f = False
print(type(t))
print(t and f, t or f, not t, t != f)

<class 'bool'>
False True False True


**Strings**: Python has great support for strings:

In [11]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = "%s %s %d" % (hello, world, 12)
print(hw12)

hello
5
hello world
hello world 12


String objects(字符串对象) have a bunch of(一系列) useful methods; for example:

In [15]:
s = "hello"
print(s.capitalize())
print(s.upper())            # Convert a string to uppercase
print(s.title())


Hello
HELLO
Hello


## Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

Python有以下几种容器类型：列表（lists）、字典（dictionaries）、集合（sets）和元组（tuples）。

## Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

列表就是Python中的数组，但是列表长度可变，且能包含不同类型元素。

In [16]:
xs = [3, 1, 2]     # Create a list
print(xs, xs[2])  
print(xs[-1])      # Negative indices count from the end of the list;
xs[2] = "foo"      # Lists can contain elements of different types, 修改列表中的元素值
print(xs)
xs.append("bar")   # Add a new element to the end of the list
print(xs)
x = xs.pop()       # Remove and return the last element of the list
print(x, xs)

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


**Slicing**: In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

为了一次性地获取列表中的元素，Python提供了一种简洁的语法，这就是切片。

In [17]:
nums = list(range(5))   # range is a built-in function that creates a list of integers
print(nums)
print(nums[2:4])        # Get a slice from index 2 to 4 (exclusive); 左闭右开区间
print(nums[2:])         # Get a slice from index 2 to the end;
print(nums[:2])         # Get a slice from the start to index 2 (exclusive);
print(nums[:])          # Get a slice of the whole list;
print(nums[:-1])        # Slice indices can be negative;
nums[2:4] = [8, 9]      # Assign a new sublist to a slice
print(nums)             

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


**Loops**: You can loop over the elements of a list like this:

In [20]:
animals = ["cat", "dog", "monkey"]
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in **`enumerate` function:**

In [22]:
animals = ["cat", "dog", "monkey"]
for inx, animal in enumerate(animals):
    print("#%d: %s" % (inx, animal))

#0: cat
#1: dog
#2: monkey


**List comprehensions(列表推导)**: When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers(平方数):

In [23]:
nums = list(range(5))
square = []
for num in nums:
    square.append(num ** 2)
print(square)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [25]:
nums = list(range(5))
even_squares = [x**2 for x in nums if x % 2 == 0]  # 从nums列表中取x， 如果x能够整除2，那么计算x平方
print(even_squares)

[0, 4, 16]


## Dictionaries

A dictionary stores (key, value) pairs. You can use it like this:

In [28]:
d = {"cat":"cute", "dog":"furry"}     # Create a new dictionary with some data
print(d["cat"])                       # Get an entry from a dictionary;
print("cat" in d)                     # Check if a dictionary has a given key;
d["fish"] = "wet"                     # Set an entry(条目) in a dictionary
print(d, d["fish"])
print("monkey" in d)
print(d.get("moneky", "N/A"))         # Get an element with a default;
print(d.get("fish", "N/A"))
del d["fish"]                         # Remove an element from a dictionary
print(d)

cute
True
{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'} wet
False
N/A
wet
{'cat': 'cute', 'dog': 'furry'}


**Loops**: It is easy to iterate over the keys in a dictionary:

In [1]:
d = {"person": 2, "cat": 4, "spider": 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the items method:

如果你想要访问键和对应的值，那就使用items方法：

In [4]:
d = {"person": 2, "cat": 4, "spider": 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [5]:
nums = list(range(5))
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


## sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

集合是独立不同个体的无序集合。

In [10]:
animals = {'cat', 'dog'}
print('cat' in animals)       # Check if an element is in a set; 
print("fish" in animals)
animals.add('fish')           # Add an element to a set
print("fish" in animals)
print(len(animals))           # Number of elements in a set;
animals.add('cat')            # Adding an element that is already in the set does nothing
print(animals)
print(len(animals))
animals.remove('cat')         # Remove an element from a set
print(animals)

True
False
True
3
{'fish', 'dog', 'cat'}
3
{'fish', 'dog'}


**Loops**:Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:
在集合中循环的语法和在列表中一样，但是集合是无序的，所以你在访问集合的元素的时候，不能做关于顺序的假设。

In [13]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print("#%d: %s" % (idx+1, animal))

#1: fish
#2: dog
#3: cat


**Set comprehensions**: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [16]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(37)}
print(nums)

{0, 1, 2, 3, 4, 5, 6}


## Tuples

A tuple is an (immutable) ordered list of values.元组是一个值的有序列表（不可改变）。 A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [18]:
d = {(x, x+1): x for x in range(10)}     # Create a dictionary with tuple keys
print(d)
t = (5, 6)
print(d[t])
print(d[(1, 2)])

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
1


## Function

Python functions are defined using the `def` keyword. For example:

In [19]:
def sign(x):
    if x > 0:
        return "positive"
    elif x < 0:
        return "negative"
    else:
        return "zero"
    
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


We will often define functions to take optional keyword arguments可选参数, like this:

In [22]:
def hello(name, loud=False):
    if loud:
        print("HELLO, %s!" % name.upper())
    else:
        print("Hello, %s!" % name)
        
hello("Bob")
hello("Fred", loud=True)

Hello, Bob!
HELLO, FRED!


## Classes

The syntax for defining classes in Python is straightforward:

In [24]:
class Greeter(object):
    # Constructor  构造函数
    def __init__(self, name):
        self.name = name          # Create an instance variable 实例变量
        
    # Instance method
    def greet(self, loud=False):
        if loud:
            print("HELLO, %s!" % self.name.upper())
        else:
            print("Hello, %s!" % self.name)

g = Greeter("Fred")                # Construct an instance of the Greeter class
g.greet()
g.greet(loud=True)

Hello, Fred!
HELLO, FRED!


# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object(高性能的多维数组对象), and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

## Arrays

A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers(可以通过非负整型数的元组来访问). The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets(方括号):

In [27]:
import numpy as np

a = np.array([1, 2, 3])    # # Create a rank 1 array
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5                   # Change an element of the array
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])     # Create a rank 2 array
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [28]:
a = np.zeros(shape=(2, 2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [29]:
b = np.ones(shape=(1, 2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [32]:
c = np.full((2,2), 9)        # Create a constant array  不接受shape=(x,x)
print(c)

[[9 9]
 [9 9]]


In [35]:
d = np.eye(2)
print(d)
f = np.random.randn(2, 2)     # Create an array filled with random values  不接受元组（）
print(f)

[[1. 0.]
 [0. 1.]]
[[-0.67659701 -0.007503  ]
 [-0.55407361 -0.80268406]]


## Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [37]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2)
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.改变切片会改变原来的值

b[0,0] = 77          # # b[0, 0] is the same piece of data as a[0, 1]
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [39]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print(col_r2, col_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing**: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [40]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example  相当于前面的整数数组索引示例
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

整型数组访问语法还有个有用的技巧，可以用来选择或者更改矩阵中每行中的一个元素：

In [41]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [42]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)                         

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes
Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [44]:
x = np.array([1, 2])    # Let numpy choose the datatype
print(x.dtype)

x = np.array([1., 2.])   # Let numpy choose the datatype
print(x.dtype)

x = np.array([1, 2], dtype="float32")  # Force a particular datatype
print(x.dtype)

int32
float64
float32


## Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [46]:
import numpy as np

# 加减乘除运算

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise(按元素) sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise(按元素) difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication(对应元素相乘), not matrix multiplication(不是矩阵点乘). We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the numpy module and as an instance method of array objects:

In [47]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [48]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [49]:
x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [50]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [51]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [52]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

    1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
    2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
    3. The arrays can be broadcast together if they are compatible in all dimensions.
    4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

Here are some applications of broadcasting:

In [69]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)


# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print((x + np.reshape(w, (2, 1))))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


# SciPy
Numpy provides a high-performance multidimensional array(高性能的多维数组) and basic tools to compute with and manipulate these arrays. SciPy builds on this, and provides a large number of functions that operate on numpy arrays and are useful for different types of scientific and engineering applications.

The best way to get familiar with SciPy is to browse the documentation. We will highlight some parts of SciPy that you might find useful for this class.


## Image operations
SciPy provides some basic functions to work with images. For example, it has functions to read images from disk into numpy arrays, to write numpy arrays to disk as images, and to resize images. Here is a simple example that showcases these functions:

In [73]:
from scipy.misc import imread, imsave, imresize
# Read an JPEG image into a numpy array
img = imread('cat.jpg')
print(img.dtype, img.shape)

# We can tint(着色) the image by scaling(缩放) each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('cat_tinted.jpg', img_tinted)

uint8 (400, 248, 3)


C:\Users\l96445\AppData\Local\Continuum\anaconda31\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\l96445\AppData\Local\Continuum\anaconda31\lib\site-packages\ipykernel_launcher.py:15: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.3.0.
Use Pillow instead: ``numpy.array(Image.fromarray(arr).resize())``.
  from ipykernel import kernelapp as app
C:\Users\l96445\AppData\Local\Continuum\anaconda31\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
